dist: bionic
sudo: false
language: haskell
cabal: "3.0"

cache:
  directories:
    - "$HOME/.cabal/store"
    - "$HOME/.stack"
    - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
    - ghc: 7.10.3
    - ghc: 8.0.2
    - ghc: 8.2.2
    - ghc: 8.4.4
    - ghc: 8.6.5
    - ghc: 8.8.1

install:
  - gcc   --version
  - ghc   --version
  - cabal --version
  - cabal update
  - cabal new-build     --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal --only-dependencies

script:
  - cabal new-configure --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal
  - cabal new-build     --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal
  - cabal new-test
  - cabal new-haddock                                                             --haddock-all --haddock-hyperlink-source --haddock-internal --haddock-for-hackage
  - cabal check

git:
  depth: 5

notifications:
  email: false
