dist: bionic
sudo: false
language: haskell
cabal: "3.0"

cache:
  directories:
    - "$HOME/.cabal/store"

matrix:
  include:
    - ghc: 8.8.1

install:
  - gcc   --version
  - ghc   --version
  - cabal --version
  - cabal update
  - cabal new-build     --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal --only-dependencies

script:
  - cabal new-configure --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal
  - cabal new-build     --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal
  - cabal new-test
  - cabal new-haddock                                                             --haddock-all --haddock-hyperlink-source --haddock-internal --haddock-for-hackage
  - cabal check

after_script:
  - export PATH=~/.cabal/bin:$PATH
  - cabal install hpc-coveralls
  - hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-dir=bench --exclude-dir=test --exclude-dir=util test-suite

git:
  depth: 5

notifications:
  email: false
