on:
  # Build every pull request, to check for regressions.
  pull_request:

  # Build when a PR is merged, to update the README's CI badge.
  push:
#    branches: [main]

  # Build once a month, to detect missing upper bounds.
  schedule:
    - cron: '0 0 1 * *'

name: build

env:
      THISPACKAGE: bv-little
      CONFIG: --enable-tests --enable-benchmarks

defaults:
  run:
    shell: bash

jobs:

  # Check that the project builds with the specified lower bounds.
  build:
    env:
      CONSTRAINTS: --project-file=cabal.project.oldest
    name: lower-bounds-check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc:   9.2.1
            cabal: latest
            os:    ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: caching lower bounds check
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          # restore keys is a fall back when the freeze plan is different
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - uses: actions/setup-haskell@v1
        name: Setup Haskell
        with:
          ghc-version:   ${{ matrix.ghc   }}
          cabal-version: ${{ matrix.cabal }}

      - run: cabal update
      - run: cabal clean
      - run: cabal configure $CONFIG $CONSTRAINTS
      - run: cabal freeze    $CONFIG $CONSTRAINTS
      - run: cabal build --only-dependencies
      - run: cabal build $CONFIG
      - run: cabal test
      - run: cabal check
      - run: cabal sdist -o `pwd`



  # Check that the build passes with the recommended snapshot.
  stack:
    name: stack-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Cache Stack Artifacts
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles(matrix.stack_yaml) }}

    - uses: haskell/actions/setup@v1
      id:   setup-haskell-stack
      name: Setup Stack
      with:
        enable-stack:    true
        stack-setup-ghc: true
        stack-no-global: true

    - name: Build
      run: |
        stack build --test --bench --no-run-tests --no-run-benchmarks
    - name: Test
      run: |
        stack test



  # Cabal build matrix
  cabal:
    name: GHC-${{ matrix.ghc }}, cabal${{matrix.cabal}}, ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc:   [ '9.2.1', 'latest' ]
        cabal: [ '3.2.0.0', '3.4.0.0', '3.6.0.0', 'latest' ]
        os:    [ ubuntu-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version:   ${{ matrix.ghc   }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal update
      - run: cabal clean
      - run: cabal configure $CONFIG $CONSTRAINTS
      - run: cabal freeze    $CONFIG $CONSTRAINTS
      - uses: actions/cache@v2
        name: windows caching
        with:
          path: |
            c:\sr
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          # restore keys is a fall back when the freeze plan is different
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
        if:  matrix.os == 'windows-latest'
      - uses: actions/cache@v2
        name: ubuntu-linux and osx caching
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          # restore keys is a fall back when the freeze plan is different
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
        if:  matrix.os != 'windows-latest'
      - run: cabal build --only-dependencies
      - run: cabal build $CONFIG
      - run: cabal check
      - run: cabal sdist -o `pwd`




